schema_version: 1

context:
  name: mo-future
  version: "7.687.26234"

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  url: https://files.pythonhosted.org/packages/source/${{ name[0] }}/${{ name }}/${{ name | replace('-', '_') }}-${{ version }}.tar.gz
  sha256: b778c2afeb446284ebc8ec3dda7278b1b71d5ed98f9779cc63ef33c57cf7ab5c

build:
  number: 0
  noarch: python
  script: ${{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python ${{ python_min }}.*
  run:
    - python >=${{ python_min }}

tests:
  - python:
      imports:
        - mo_future
      pip_check: true
      python_version:
        - ${{ python_min }}.*
        - '*'

about:
  license: MPL-2.0
  license_file: LICENSE
  summary: More future! Make Python 2/3 compatibility a bit easier
  homepage: https://github.com/klahnakoski/mo-files

extra:
  recipe-maintainers:
    - xhochy
